# Generated by Django 3.1.7 on 2021-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210422_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallrypic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('textpara', models.CharField(max_length=300)),
            ],
        ),
    ]
