# Generated by Django 3.1.7 on 2021-04-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_gallrypic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallrypic',
            new_name='Gallary',
        ),
    ]
