# Generated by Django 3.1.7 on 2021-04-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210425_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallary',
            name='image',
        ),
    ]
