# Generated by Django 3.1.7 on 2021-04-26 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_gallary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallary',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dogname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='textpara',
            field=models.CharField(default='', max_length=300),
        ),
    ]
